services:

  ams-front-app:
    container_name: ams-front
    image: llhwanll/ams-front:latest
    environment:
      - REACT_APP_API_URL=http://192.168.9.197:8888
      - REACT_APP_LANG=ko
    ports:
      - "3000:80"
    networks:
      - ams_network
    expose:
      - 3000


  ams-backend-app:
    container_name: ams-backend
    image: hoonseung/asset-management:latest

    
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}

      - FORMAT_SQL=false
      - SHOW_SQL=false

      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}

      - CAFFEINE_MAX_SIZE=${CAFFEINE_MAX_SIZE}
      - CAFFEINE_MINUTE=${CAFFEINE_MINUTE}
      - CAFFEINE_DAY=${CAFFEINE_DAY}

      - JWT_SECRET=${JWT_SECRET}
      - JWT_ACCESS_EXPIRE=${JWT_ACCESS_EXPIRE}
      - JWT_REFRESH_EXPIRE=${JWT_REFRESH_EXPIRE}


    volumes:
      - /data/app/logs:/app/logs

    ports:
      - "8888:8888"
    networks:
      - ams_network

networks:
  ams_network:
    driver: bridge
