services:
  postgres:
    container_name: ams-postgres
    image: postgres:14.4
    ports:
      - "5432:5432"

    restart: on-failure

    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - ams_network



  redis:
    container_name: ams-redis
    image: redis:7.0
    ports:
      - "6379:6379"

    restart: on-failure

    environment:
      - ALLOW_EMPTY_PASSWORD=yes

    volumes:
      - redis_data:/data

    networks:
      - ams_network

  rabbitmq:
    container_name: ams-rabbitmq
    image: rabbitmq:4.0-management
    ports:
      - "5672:5672"
      - "15672:15672"

    restart: on-failure
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PASS}

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq

    networks:
      - ams_network

volumes:
  pg_data:
  redis_data:
  rabbitmq_data:
  rabbitmq_logs:

networks:
  ams_network:
    driver: bridge
